
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int suma = 14;
  public static final int puntos = 30;
  public static final int resta = 15;
  public static final int llac = 11;
  public static final int llaa = 10;
  public static final int coma = 33;
  public static final int igual = 32;
  public static final int definirxyline = 34;
  public static final int string = 22;
  public static final int caracter = 7;
  public static final int graficalineas = 36;
  public static final int EOF = 0;
  public static final int parc = 20;
  public static final int para = 19;
  public static final int nombre = 27;
  public static final int error = 1;
  public static final int corc = 13;
  public static final int color = 28;
  public static final int cora = 12;
  public static final int entero = 2;
  public static final int graficabarras = 35;
  public static final int dospuntos = 9;
  public static final int potencia = 18;
  public static final int id = 6;
  public static final int galeria = 40;
  public static final int multi = 16;
  public static final int tituloy = 26;
  public static final int prec = 41;
  public static final int titulox = 25;
  public static final int titulo = 24;
  public static final int grosor = 29;
  public static final int prea = 42;
  public static final int ink = 21;
  public static final int puntocoma = 8;
  public static final int booleano = 5;
  public static final int puntosxy = 39;
  public static final int div = 17;
  public static final int globales = 31;
  public static final int ejey = 38;
  public static final int ejex = 37;
  public static final int decimal = 3;
  public static final int idt = 23;
  public static final int cadena = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "entero",
  "decimal",
  "cadena",
  "booleano",
  "id",
  "caracter",
  "puntocoma",
  "dospuntos",
  "llaa",
  "llac",
  "cora",
  "corc",
  "suma",
  "resta",
  "multi",
  "div",
  "potencia",
  "para",
  "parc",
  "ink",
  "string",
  "idt",
  "titulo",
  "titulox",
  "tituloy",
  "nombre",
  "color",
  "grosor",
  "puntos",
  "globales",
  "igual",
  "coma",
  "definirxyline",
  "graficabarras",
  "graficalineas",
  "ejex",
  "ejey",
  "puntosxy",
  "galeria",
  "prec",
  "prea"
  };
}

