
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ancho = 44;
  public static final int textob = 39;
  public static final int textoa = 38;
  public static final int salto = 20;
  public static final int echo = 56;
  public static final int getpath = 83;
  public static final int corc = 64;
  public static final int punto = 57;
  public static final int borde = 49;
  public static final int idboton = 46;
  public static final int cora = 63;
  public static final int compi = 23;
  public static final int booleano = 5;
  public static final int setcontenido = 77;
  public static final int suma = 9;
  public static final int setalto = 84;
  public static final int imagen = 40;
  public static final int llac = 62;
  public static final int anddoble = 59;
  public static final int elses = 93;
  public static final int llaa = 61;
  public static final int rgb = 30;
  public static final int especialista = 96;
  public static final int boton = 45;
  public static final int div = 12;
  public static final int may = 17;
  public static final int resta = 10;
  public static final int getancho = 87;
  public static final int clickboton = 92;
  public static final int cadena = 4;
  public static final int menorigual = 67;
  public static final int color = 29;
  public static final int insertar = 73;
  public static final int estado = 50;
  public static final int crearparrafo = 74;
  public static final int decimal = 3;
  public static final int getcontenido = 78;
  public static final int getalto = 85;
  public static final int basura = 95;
  public static final int dolar = 55;
  public static final int fila = 51;
  public static final int columnac = 52;
  public static final int settexto = 90;
  public static final int or = 66;
  public static final int caracter = 7;
  public static final int fondo = 27;
  public static final int mayorigual = 68;
  public static final int id = 6;
  public static final int alineacion = 21;
  public static final int textoboton = 47;
  public static final int parrafo = 32;
  public static final int path = 41;
  public static final int alip = 37;
  public static final int hs = 54;
  public static final int ifv = 58;
  public static final int setborder = 88;
  public static final int columna = 53;
  public static final int tabla = 48;
  public static final int titulo = 25;
  public static final int puntocoma = 8;
  public static final int and = 65;
  public static final int esp = 15;
  public static final int interro = 16;
  public static final int espacio = 31;
  public static final int cabecera = 24;
  public static final int derecha = 34;
  public static final int crearboton = 89;
  public static final int men = 18;
  public static final int centrado = 35;
  public static final int creartextob = 80;
  public static final int creartextoa = 79;
  public static final int EOF = 0;
  public static final int repetir = 71;
  public static final int cuerpo = 26;
  public static final int alto = 43;
  public static final int multi = 11;
  public static final int imgdir = 42;
  public static final int crearimagen = 81;
  public static final int error = 1;
  public static final int numeral = 72;
  public static final int setancho = 86;
  public static final int diferente = 69;
  public static final int gettexto = 91;
  public static final int entero = 2;
  public static final int izquierda = 33;
  public static final int admira = 19;
  public static final int igualdoble = 70;
  public static final int comen = 22;
  public static final int parc = 14;
  public static final int para = 13;
  public static final int ordoble = 60;
  public static final int coma = 94;
  public static final int justificado = 36;
  public static final int igual = 28;
  public static final int setpath = 82;
  public static final int creartabla = 97;
  public static final int getalineacion = 76;
  public static final int setalineacion = 75;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "entero",
  "decimal",
  "cadena",
  "booleano",
  "id",
  "caracter",
  "puntocoma",
  "suma",
  "resta",
  "multi",
  "div",
  "para",
  "parc",
  "esp",
  "interro",
  "may",
  "men",
  "admira",
  "salto",
  "alineacion",
  "comen",
  "compi",
  "cabecera",
  "titulo",
  "cuerpo",
  "fondo",
  "igual",
  "color",
  "rgb",
  "espacio",
  "parrafo",
  "izquierda",
  "derecha",
  "centrado",
  "justificado",
  "alip",
  "textoa",
  "textob",
  "imagen",
  "path",
  "imgdir",
  "alto",
  "ancho",
  "boton",
  "idboton",
  "textoboton",
  "tabla",
  "borde",
  "estado",
  "fila",
  "columnac",
  "columna",
  "hs",
  "dolar",
  "echo",
  "punto",
  "ifv",
  "anddoble",
  "ordoble",
  "llaa",
  "llac",
  "cora",
  "corc",
  "and",
  "or",
  "menorigual",
  "mayorigual",
  "diferente",
  "igualdoble",
  "repetir",
  "numeral",
  "insertar",
  "crearparrafo",
  "setalineacion",
  "getalineacion",
  "setcontenido",
  "getcontenido",
  "creartextoa",
  "creartextob",
  "crearimagen",
  "setpath",
  "getpath",
  "setalto",
  "getalto",
  "setancho",
  "getancho",
  "setborder",
  "crearboton",
  "settexto",
  "gettexto",
  "clickboton",
  "elses",
  "coma",
  "basura",
  "especialista",
  "creartabla"
  };
}

