
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int dop = 42;
  public static final int admira = 18;
  public static final int suma = 9;
  public static final int resta = 10;
  public static final int functionpp = 46;
  public static final int flecha = 48;
  public static final int llac = 26;
  public static final int llaa = 25;
  public static final int interro = 15;
  public static final int coma = 34;
  public static final int elses = 33;
  public static final int igual = 19;
  public static final int men = 17;
  public static final int casep = 38;
  public static final int caracter = 7;
  public static final int ifv = 22;
  public static final int igualdoble = 32;
  public static final int whilep = 41;
  public static final int returnp = 45;
  public static final int may = 16;
  public static final int EOF = 0;
  public static final int suitc = 37;
  public static final int parc = 14;
  public static final int breakp = 40;
  public static final int para = 13;
  public static final int error = 1;
  public static final int corc = 28;
  public static final int cora = 27;
  public static final int entero = 2;
  public static final int or = 24;
  public static final int menorigual = 29;
  public static final int punto = 21;
  public static final int forp = 43;
  public static final int defaultp = 39;
  public static final int potencia = 35;
  public static final int id = 6;
  public static final int doblepunto = 20;
  public static final int continuep = 44;
  public static final int multi = 11;
  public static final int inp = 47;
  public static final int mayorigual = 30;
  public static final int diferente = 31;
  public static final int puntocom = 8;
  public static final int and = 23;
  public static final int booleano = 5;
  public static final int modular = 36;
  public static final int div = 12;
  public static final int decimal = 3;
  public static final int cadena = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "entero",
  "decimal",
  "cadena",
  "booleano",
  "id",
  "caracter",
  "puntocom",
  "suma",
  "resta",
  "multi",
  "div",
  "para",
  "parc",
  "interro",
  "may",
  "men",
  "admira",
  "igual",
  "doblepunto",
  "punto",
  "ifv",
  "and",
  "or",
  "llaa",
  "llac",
  "cora",
  "corc",
  "menorigual",
  "mayorigual",
  "diferente",
  "igualdoble",
  "elses",
  "coma",
  "potencia",
  "modular",
  "suitc",
  "casep",
  "defaultp",
  "breakp",
  "whilep",
  "dop",
  "forp",
  "continuep",
  "returnp",
  "functionpp",
  "inp",
  "flecha"
  };
}

