/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visuales;

import Listas.*;
import static Visuales.CargarDatos.Usu;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class MenuUsuarios extends javax.swing.JFrame {

    
    public static int IDUsuario=1000,ult=0;
    
    
    /**
     * Creates new form MenuUsuarios
     */
    public MenuUsuarios() {

        initComponents();
        super.setBounds(0,0,630,485);
        super.setLocationRelativeTo(null);
       // super.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButton1.setText("Sobre Dorado");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(350, 60, 220, 240);

        jButton2.setText("Sobre Normal");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 60, 220, 240);

        jTabbedPane1.addTab("Abrir Sobres", jPanel1);

        jPanel3.setLayout(null);
        jTabbedPane1.addTab("Ver Estampas", jPanel3);

        jPanel4.setLayout(null);
        jTabbedPane1.addTab("Ver Equipos O Jugadores", jPanel4);

        jPanel5.setLayout(null);
        jTabbedPane1.addTab("Mi Colección", jPanel5);

        jPanel6.setLayout(null);

        jButton9.setText("Reportes");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);
        jButton9.setBounds(210, 110, 320, 200);

        jButton10.setText("LogOut");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10);
        jButton10.setBounds(60, 140, 69, 140);

        jTabbedPane1.addTab("Reportes", jPanel6);

        jPanel2.setLayout(null);

        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(100, 90, 60, 150);

        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(180, 90, 180, 240);

        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(100, 200, 60, 130);

        jButton4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton4.setText("Colocar");
        jButton4.setActionCommand("Colocar Estampa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(460, 190, 140, 40);

        jButton5.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButton5.setText("←");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(10, 90, 70, 240);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("1");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(340, 50, 60, 40);

        jButton6.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButton6.setText("→");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(370, 90, 70, 240);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 340, 290, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("jLabel5");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(90, 370, 290, 19);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setText("Estampa Actual");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(100, 50, 280, 40);

        jButton7.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButton7.setText("→");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(470, 10, 70, 30);

        jButton8.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButton8.setText("←");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(170, 10, 70, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel8.setText("Sobre Actual");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 0, 280, 40);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel9.setText("1");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(340, 10, 60, 40);

        jTabbedPane1.addTab("Ver Sobres", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 610, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static         String[][] Estampas = new String[10][5];
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        for(int i=0;i<10;i++){Estampas[i][0]=null;Estampas[i][1]=null;Estampas[i][2]=null;Estampas[i][3]=null;Estampas[i][4]=null;}
        int lim = (int) (Math.random() * 2) + 4+(int) (Math.random() * 2);
        int numero=0;
        System.out.println(lim);
        ult=lim;
        for(int i=0;i<lim;i++){
        numero=i;
        NodoEstampas Sobre=EnlaceEstampas.Inicio;
        int tope = (int) (Math.random() * (EnlaceEstampas.Contador-2)) + 1;
            for(int j=0;j<tope;j++){
             Sobre=Sobre.Siguiente;
            }
            Estampas[i][0]=""+Sobre.ID;
            Estampas[i][1]=""+Sobre.IDJugador;
            Estampas[i][2]=""+Sobre.IDEquipo;
            Estampas[i][3]=Sobre.Rareza;
            Estampas[i][4]=Sobre.RutaImagen;
         for(int l=0;l<numero;l++){if(Estampas[l][0].equals(Estampas[i][0])){i=numero-1;}}
        }
        
        
        for(int i=0;i<10;i++){
            System.out.println("////////////////");
          //  System.out.println(Estampas[i][0]);
          //  System.out.println(Estampas[i][1]);
           // System.out.println(Estampas[i][2]);
           // System.out.println(Estampas[i][3]);
            System.out.println(Estampas[i][4]);
        }
        EnlaceEstampasUsuarios Enla = new EnlaceEstampasUsuarios();
        EnlaceRepetidas Repe = new EnlaceRepetidas();
        NodoRepetidas Copia;
        
        
         for(int i=0;i<lim;i++){
             Copia=Repe.Existencia(Integer.parseInt(Estampas[i][0]));
             if(Copia!=null){
                 
                 Copia.Cantidad=Copia.Cantidad+1;
             }
             else{ 
                 Enla.Agregar(IDUsuario, Integer.parseInt(Estampas[i][0]),"0", 1);
                 Repe.Agregar(IDUsuario, Integer.parseInt(Estampas[i][0]),"0", 0);
             }
         
         }
        Enla.LimpiarSobre();
        Boton();
        Sobres Sobres = new Sobres();
        Sobres.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

  public static int MaxSobres=0;
    
    private void Boton(){
EnlaceUsuarios Usuarios = new EnlaceUsuarios();
MaxSobres=0;
        int l = 0;
        //jLabel2.setText("" + a);

        //Crear Sobres
        Usuarios.ImprimirOrden();

        EnlaceEstampasUsuarios EU = new EnlaceEstampasUsuarios();
        Usuarios.PreSacar();
        
        while (true) {             int a = Usuarios.SacarValores(l);
            System.out.println(a);

            if (l == a) { break;
            }
             int MaxSobres = (int) (Math.random() * 4) + 4;
             int Sobre=0;
             int t; 
             
            while(true)
            {Sobre++;MaxSobres++;
                while (true) {

                     t = EU.CrearSobres(a, Sobre, MaxSobres);
                    if (t >= -3) {
                        break;
                    }
                }
                if(t>=1){break;}
                
            }l=a;
        }
        EU.Imprimir();


}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    for(int i=0;i<10;i++){Estampas[i][0]=null;Estampas[i][1]=null;Estampas[i][2]=null;Estampas[i][3]=null;Estampas[i][4]=null;}
        int especiales=0;
        
        int lim = (int) (Math.random() * 2) + 5+(int) (Math.random() * 2)+(int) (Math.random() * 1);
        int numero=0;
        System.out.println(lim);
        ult=lim;
        for(int i=0;i<lim;i++){
            
            
        numero=i;
        
        
        NodoEstampas Sobre=EnlaceEstampas.Inicio;
        int tope = (int) (Math.random() * (EnlaceEstampas.Contador-2)) + 1;
        
        
            for(int j=0;j<tope;j++){
             Sobre=Sobre.Siguiente;
            }
            
            
            Estampas[i][0]=""+Sobre.ID;
            Estampas[i][1]=""+Sobre.IDJugador;
            Estampas[i][2]=""+Sobre.IDEquipo;
            Estampas[i][3]=Sobre.Rareza;
            Estampas[i][4]=Sobre.RutaImagen;
            
            
           // while(true){}
            
         if(Estampas[i][3].equals("0")&&(especiales<((int)lim/2))){i=numero-1;}  else{
           especiales++;
         for(int l=0;l<numero;l++){if(Estampas[l][0].equals(Estampas[i][0])){i=numero-1;}}
         }
        }
        
        
        for(int i=0;i<10;i++){
            System.out.println("////////////////");
          //  System.out.println(Estampas[i][0]);
          //  System.out.println(Estampas[i][1]);
           // System.out.println(Estampas[i][2]);
           // System.out.println(Estampas[i][3]);
            System.out.println(Estampas[i][4]);
        
        
        }
        EnlaceEstampasUsuarios Enla = new EnlaceEstampasUsuarios();
        EnlaceRepetidas Repe = new EnlaceRepetidas();
        NodoRepetidas Copia;
        
        
         for(int i=0;i<lim;i++){
             Copia=Repe.Existencia(Integer.parseInt(Estampas[i][0]));
             if(Copia!=null){
                 
                 Copia.Cantidad=Copia.Cantidad+1;
                 
                
           
             
             
             }
             else{ 
                 Enla.Agregar(IDUsuario, Integer.parseInt(Estampas[i][0]),"0", 1);
                 Repe.Agregar(IDUsuario, Integer.parseInt(Estampas[i][0]),"0", 0);
             
             
             }
         
         }
        
        Enla.LimpiarSobre();
        Boton();
        
        
        Sobres Sobres = new Sobres();
        Sobres.setVisible(true);
        
        this.setVisible(false);
        

        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        EnlaceEstampasUsuarios Enla = new EnlaceEstampasUsuarios();

        
        EnlaceRepetidas Repe = new EnlaceRepetidas();

        NodoRepetidas Rep = Repe.Existencia(IDEstampa);
        if (Rep.Pegada.equals("1")) {
            JOptionPane.showMessageDialog(null, "Esta Estampa U Otra del mismo tipo Ya Ha Sido Pegada ");
        } else {
            Rep.Pegada = "1";
            Rep.Cantidad = Rep.Cantidad + 1;
            EnlaceEstampasUsuarios Enl = new EnlaceEstampasUsuarios();
            NodoEstampasUsuario EstamU = Enl.Existencia(IDEstampa);
            if (EstamU != null) {
                Enl.Limpiar(EstamU);
            } else {
                JOptionPane.showMessageDialog(null, "Nulo");
            }

            JOptionPane.showMessageDialog(null, "Estampa Colocada En El Álbum");
        }
        
        
        
        
        
        
        
        
        
        
        Enla.LimpiarSobre();
        Boton();
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        


        EnlaceEstampasUsuarios Enla = new EnlaceEstampasUsuarios();
        EnlaceRepetidas Repetidas = new EnlaceRepetidas();
        EnlaceEstampas Estampa= new EnlaceEstampas();
        EnlaceJugadores Jugadores = new EnlaceJugadores();
        EnlaceEquipos Equipos = new EnlaceEquipos();
        
        int Sobre=Integer.parseInt(jLabel9.getText());
        int Index=Integer.parseInt(jLabel4.getText())-1;
        
        int Max=Enla.MaxEstampa(IDUsuario,Sobre);
        System.out.println(Max);
        
        if(Index<1){Index=Max;}

        
        jLabel4.setText(""+Index);
        //El Actual -_- 
        System.out.println(Sobre+"  " +Index);
        NodoEstampasUsuario Actual=Enla.SacarEstampa(Sobre, Index);
        
        
        
        if(Actual==null&&Sobre!=0){jLabel4.setText("1");Index=1;}Actual=Enla.SacarEstampa(Sobre, Index);
        

        if(Sobre==0){
            jLabel4.setText("1");
          //  JOptionPane.showMessageDialog(null, Repetid);
            Repetid = Repetidas.SiguienteNodo2(Repetid);
         //   JOptionPane.showMessageDialog(null, Repetid);
        
        }
        if(Repetid==null){Pri=Repetid;}
        //if(Anter==0){Sobre=1;Actual=Enla.SacarEstampa(Sobre, Index);        jLabel9.setText(""+(Sobre));}

      //  Anter=Sobre;

        
        NodoEstampas Estam=null;
        System.out.println("AQUI");
        if(Actual!=null){
            IDEstampa=Actual.IDEstampas;
            System.out.println(Actual.IDEstampas);
            Estam=Estampa.SacarEstampa(Actual.IDEstampas);
            System.out.println(Estam.RutaImagen);
            jLabel2.setIcon(new ImageIcon(Estam.RutaImagen));
            jLabel6.setText(Equipos.DevolverEquipo(Estam.IDEquipo));
            jLabel5.setText(Jugadores.DevolverJugador(Estam.IDJugador));
        }
       if(Sobre==0){
           IDEstampa=No.IDEstampas;
          Estam=Estampa.SacarEstampa(Repetid.IDEstampas);
          jLabel2.setIcon(new ImageIcon(Estam.RutaImagen));
          jLabel6.setText(Equipos.DevolverEquipo(Estam.IDEquipo));
          jLabel5.setText(Jugadores.DevolverJugador(Estam.IDJugador));
       }
        
        
        
        
         if (Estam.Rareza.equals("0")) {
            jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
            jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        } else {

            jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
            jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    static NodoRepetidas  Repetid=null;
    static NodoRepetidas  Pri=null;
    
    int IDEstampa;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        


        EnlaceEstampasUsuarios Enla = new EnlaceEstampasUsuarios();
        EnlaceRepetidas Repetidas = new EnlaceRepetidas();
        EnlaceEstampas Estampa= new EnlaceEstampas();
        EnlaceJugadores Jugadores = new EnlaceJugadores();
        EnlaceEquipos Equipos = new EnlaceEquipos();
        int Index=Integer.parseInt(jLabel4.getText())+1;
        

        int Sobre=Integer.parseInt(jLabel9.getText());
        
        jLabel4.setText(""+Index);
        //El Actual -_- 
        System.out.println(Sobre+"  " +Index);
        NodoEstampasUsuario Actual=Enla.SacarEstampa(Sobre, Index);
        
        
        
        if(Actual==null&&Sobre!=0){jLabel4.setText("1");Index=1;}Actual=Enla.SacarEstampa(Sobre, Index);
        

        if(Sobre==0){
            jLabel4.setText("1");
          //  JOptionPane.showMessageDialog(null, Repetid);
            Repetid = Repetidas.SiguienteNodo2(Repetid);
         //   JOptionPane.showMessageDialog(null, Repetid);
        
        }
        if(Repetid==null){Pri=Repetid;}
        //if(Anter==0){Sobre=1;Actual=Enla.SacarEstampa(Sobre, Index);        jLabel9.setText(""+(Sobre));}

      //  Anter=Sobre;

        
        NodoEstampas Estam=null;
        System.out.println("AQUI");
        if(Actual!=null){
            IDEstampa=Actual.IDEstampas;
            System.out.println(Actual.IDEstampas);
            Estam=Estampa.SacarEstampa(Actual.IDEstampas);
            System.out.println(Estam.RutaImagen);
            jLabel2.setIcon(new ImageIcon(Estam.RutaImagen));
            jLabel6.setText(Equipos.DevolverEquipo(Estam.IDEquipo));
            jLabel5.setText(Jugadores.DevolverJugador(Estam.IDJugador));
        }
       if(Sobre==0){
           IDEstampa=No.IDEstampas;
          Estam=Estampa.SacarEstampa(Repetid.IDEstampas);
          jLabel2.setIcon(new ImageIcon(Estam.RutaImagen));
          jLabel6.setText(Equipos.DevolverEquipo(Estam.IDEquipo));
          jLabel5.setText(Jugadores.DevolverJugador(Estam.IDJugador));
       }
        
        
        
        
         if (Estam.Rareza.equals("0")) {
            jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
            jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        } else {

            jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
            jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        }
    //    

    }//GEN-LAST:event_jButton6ActionPerformed
    private NodoRepetidas No=null;
    static int Anter=31931;
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed



        EnlaceEstampasUsuarios Enla = new EnlaceEstampasUsuarios();
        EnlaceRepetidas Repetidas = new EnlaceRepetidas();
        EnlaceEstampas Estampa= new EnlaceEstampas();
        EnlaceJugadores Jugadores = new EnlaceJugadores();
        EnlaceEquipos Equipos = new EnlaceEquipos();
        int Index=1;
        

        int Sobre=Integer.parseInt(jLabel9.getText())+1;
        jLabel9.setText(""+(Sobre));
        jLabel4.setText(""+Index);
        //El Actual -_- 
        System.out.println(Sobre);
        NodoEstampasUsuario Actual=Enla.SacarEstampa(Sobre, Index);
        
        
        
        if(Actual==null){jLabel9.setText(""+0);}
        
        Sobre=Integer.parseInt(jLabel9.getText());

        if(Sobre==0){No = Repetidas.SiguienteNodo(No);}
        
        //if(Anter==0){Sobre=1;Actual=Enla.SacarEstampa(Sobre, Index);        jLabel9.setText(""+(Sobre));}

      //  Anter=Sobre;

        
        NodoEstampas Estam;
        System.out.println("AQUI");
        if(Actual!=null){
            IDEstampa=Actual.IDEstampas;
            System.out.println(Actual.IDEstampas);
            Estam=Estampa.SacarEstampa(Actual.IDEstampas);
            System.out.println(Estam.RutaImagen);
            jLabel2.setIcon(new ImageIcon(Estam.RutaImagen));
            jLabel6.setText(Equipos.DevolverEquipo(Estam.IDEquipo));
            jLabel5.setText(Jugadores.DevolverJugador(Estam.IDJugador));
        }
        else{
            IDEstampa=No.IDEstampas;
           Estam=Estampa.SacarEstampa(No.IDEstampas);
          jLabel2.setIcon(new ImageIcon(Estam.RutaImagen));
          jLabel6.setText(Equipos.DevolverEquipo(Estam.IDEquipo));
          jLabel5.setText(Jugadores.DevolverJugador(Estam.IDJugador));
       }
        
        
        if (Estam.Rareza.equals("0")) {
            jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
            jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        } else {

            jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
            jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        }
        
         if (Estam.Rareza.equals("0")) {
            jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
            jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        } else {

            jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
            jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        }
    //    
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        
        EnlaceEstampasUsuarios Enla = new EnlaceEstampasUsuarios();
        EnlaceRepetidas Repetidas = new EnlaceRepetidas();
        EnlaceEstampas Estampa= new EnlaceEstampas();
        EnlaceJugadores Jugadores = new EnlaceJugadores();
        EnlaceEquipos Equipos = new EnlaceEquipos();
        int Index=1;
        
        int Max=Enla.MaxSobre(IDUsuario);

        int Sobre=Integer.parseInt(jLabel9.getText())-1;
        System.out.println("Maximo      "+MaxSobres);
        if(Sobre<0){Sobre=Max;}
        
        jLabel9.setText(""+(Sobre));
        jLabel4.setText(""+Index);
        //El Actual -_- 
        System.out.println(Sobre);
        NodoEstampasUsuario Actual=Enla.SacarEstampa(Sobre, Index);
        
        
        
        if(Actual==null){jLabel9.setText(""+0);}
        
        Sobre=Integer.parseInt(jLabel9.getText());

        if(Sobre==0){No = Repetidas.SiguienteNodo(No);}
        
        //if(Anter==0){Sobre=1;Actual=Enla.SacarEstampa(Sobre, Index);        jLabel9.setText(""+(Sobre));}

      //  Anter=Sobre;

        
        NodoEstampas Estam;
        System.out.println("AQUI");
         if(Actual!=null){
            IDEstampa=Actual.IDEstampas;
            System.out.println(Actual.IDEstampas);
            Estam=Estampa.SacarEstampa(Actual.IDEstampas);
            System.out.println(Estam.RutaImagen);
            jLabel2.setIcon(new ImageIcon(Estam.RutaImagen));
            jLabel6.setText(Equipos.DevolverEquipo(Estam.IDEquipo));
            jLabel5.setText(Jugadores.DevolverJugador(Estam.IDJugador));
        }
        else{
          IDEstampa=No.IDEstampas;   
          
          Estam=Estampa.SacarEstampa(No.IDEstampas);
          jLabel2.setIcon(new ImageIcon(Estam.RutaImagen));
          jLabel6.setText(Equipos.DevolverEquipo(Estam.IDEquipo));
          jLabel5.setText(Jugadores.DevolverJugador(Estam.IDJugador));
       }
    //    
        
        


    }//GEN-LAST:event_jButton8ActionPerformed
int ReporteUsuario1(int IDE){
     int valor=0;
    NodoRepetidas Imprimir=EnlaceRepetidas.Cuerpo.Siguiente;
    while(Imprimir.Siguiente!=EnlaceRepetidas.Cabeza){
       
        
        if((Imprimir.IDEstampas==IDE)){valor=(valor+Imprimir.Cantidad+1);}
        
        Imprimir=Imprimir.Siguiente;
    }
    
         
         return valor;
    }
    
    int ReporteUsuario2(int IDE){
     int valor=0;
    EnlaceEstampas Estampas = new EnlaceEstampas();
    NodoRepetidas Imprimir=EnlaceRepetidas.Cuerpo.Siguiente;
    while(Imprimir.Siguiente!=EnlaceRepetidas.Cabeza){
       
        int prueba;
        //NodoEstampas Estam=Estampas.DevolverEquipoEstampa(Imprimir.IDEstampas);
        prueba=Estampas.DevolverEquipoEstampa(Imprimir.IDEstampas);
        
        if((prueba==IDE)&&(Imprimir.Pegada.equals("1"))){valor=(valor+Imprimir.Cantidad+1);}
        
        Imprimir=Imprimir.Siguiente;
    }
    
         
         return valor;
    }
    
    
    
    
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
            EnlaceEstampas Estampas= new EnlaceEstampas();
        NodoEstampas Actual=null;
        
        
        
        String[][] Datos = new String[EnlaceRepetidas.Repetidas][2];
        for(int i=0;i<EnlaceRepetidas.Repetidas;i++){
            Actual=Estampas.SacarSiguiente(Actual);
            
            Datos[i][0]=""+Actual.ID;
            Datos[i][1]=""+ReporteUsuario1(Actual.ID);    
        }
       
       
        
        for (int j = 0; j < EnlaceRepetidas.Repetidas; j++) {

            for (int i = 0; i < EnlaceRepetidas.Repetidas - 1; i++) {
                if (Integer.parseInt(Datos[i][1]) < Integer.parseInt(Datos[i+1][1])) {
                    int Copia=Integer.parseInt(Datos[i][1]);
                    String CopiaS=Datos[i][0];

                    Datos[i][0]=Datos[i+1][0];
                    Datos[i][1]=Datos[i+1][1];
                    
                    Datos[i+1][0]=""+CopiaS;
                    Datos[i+1][1]=""+Copia;
                    
                    
                }
                
                

            }
            
        }
        
        
        
       
        
         Actual=null;
        
        NodoEquipos Actualidad=null;
        EnlaceEquipos Equipos = new EnlaceEquipos();
        String[][] DatosE = new String[EnlaceEquipos.CantidadEquipos+2][2+2];
        
        
        
        for(int i=0;i<EnlaceEquipos.CantidadEquipos;i++){
            Actualidad=Equipos.SacarSiguiente(Actualidad);
            
            DatosE[i][0]=""+Actualidad.Num;
            DatosE[i][1]=""+ReporteUsuario2(Actualidad.Num);    
        }
       
       
        
        for (int j = 0; j < EnlaceEquipos.CantidadEquipos; j++) {

            for (int i = 0; i < EnlaceEquipos.CantidadEquipos - 1; i++) {
                if (Integer.parseInt(DatosE[i][1]) < Integer.parseInt(DatosE[i+1][1])) {
                    int Copia=Integer.parseInt(DatosE[i][1]);
                    String CopiaS=DatosE[i][0];

                    DatosE[i][0]=DatosE[i+1][0];
                    DatosE[i][1]=DatosE[i+1][1];
                    
                    DatosE[i+1][0]=""+CopiaS;
                    DatosE[i+1][1]=""+Copia;
                    
                    
                }
                
                

            }
            
        }
        
        
        
        
        
        
        
        
        
        System.out.println("///////////////////////////");
        System.out.println("Top 5 Equipos con más Estampas");
         for(int i=0;i<EnlaceEquipos.CantidadEquipos;i++){
            System.out.println("Equipo "+DatosE[i][0]);
            System.out.println("Cantidad  "+DatosE[i][1]);
            
            
            }

         
         System.out.println("///////////////////////////");
        System.out.println("Top 5 Equipos con más Estampas");
         for(int i=EnlaceEquipos.CantidadEquipos-1;i>=0;i--){
            System.out.println("Equipo "+DatosE[i][0]);
            System.out.println("Cantidad  "+DatosE[i][1]);
            
            
            }
         
         
          Document document = new Document();
         
        try{
            PdfWriter.getInstance(document, new FileOutputStream("ReporteUsuario.pdf"));
            document.open();
             
            PdfPTable table = new PdfPTable(2);                
             
            PdfPCell celdaFinal = new PdfPCell(new Paragraph("Top Estampas mas repetidas"));
            celdaFinal.setColspan(2);
            table.addCell(celdaFinal);
            table.addCell("Codigo De Estampa");
            table.addCell("Cantidad De Estampas");

         for(int i=0;i<EnlaceRepetidas.Repetidas;i++){
           table.addCell(Datos[i][0]);
           table.addCell(Datos[i][1]);
            }
            
            
            celdaFinal = new PdfPCell(new Paragraph("Total sobres abiertos"));
            celdaFinal.setColspan(2);
            table.addCell(celdaFinal);
            table.addCell("Codigo De Usuario");
            table.addCell("Cantidad De Sobres Abiertos");

            
            celdaFinal = new PdfPCell(new Paragraph("Total de equipos con más Estampas"));
            celdaFinal.setColspan(2);
            table.addCell(celdaFinal);
            table.addCell("Codigo De Equipo");
            table.addCell("Cantidad De Estampas");
            
            
            
           for(int i=0;i<EnlaceEquipos.CantidadEquipos;i++){
            table.addCell(DatosE[i][0]);
            table.addCell(DatosE[i][1]);
            }
            
            
            celdaFinal = new PdfPCell(new Paragraph("Total de equipos con menos Estampas"));
            celdaFinal.setColspan(2);
            table.addCell(celdaFinal);
            table.addCell("Codigo De Equipo");
            table.addCell("Cantidad De Estampas");

           for(int i=EnlaceEquipos.CantidadEquipos-1;i>=0;i--){
            table.addCell(DatosE[i][0]);
            table.addCell(DatosE[i][1]);
            }
            
            document.add(table);
             
            document.close();
             
        }catch(Exception e)
        {
            System.err.println("Ocurrio un error al crear el archivo");
            System.exit(-1);
        }
         


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        NewJFrame Abrir = new NewJFrame();
    Abrir.setVisible(true);
    this.setVisible(false);

    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
