/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visuales;
import Listas.*;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Sobres extends javax.swing.JFrame {

    /**
     * Creates new form Sobres
     */
    public Sobres() {
        initComponents();
        super.setBounds(0,0,580,520);
        super.setLocationRelativeTo(null);
        super.setResizable(false);
        
       
        jLabel2.setIcon(new ImageIcon(MenuUsuarios.Estampas[0][4]));
        
        EnlaceJugadores Jugadores = new EnlaceJugadores();
        EnlaceEquipos Equipos = new EnlaceEquipos();
        
        
        if(MenuUsuarios.Estampas[0][3].equals("0")){
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        }else{
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));}
        
        
        
        
        
        jLabel5.setText(Jugadores.DevolverJugador(Integer.parseInt(MenuUsuarios.Estampas[0][1])));
        jLabel6.setText(Equipos.DevolverEquipo(Integer.parseInt(MenuUsuarios.Estampas[0][2])));
                System.out.println(MenuUsuarios.ult);

        
          if(MenuUsuarios.Estampas[0][3].equals("0")){
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        }else{
            
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 110, 60, 240);

        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 110, 180, 240);

        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 110, 60, 240);

        jButton1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButton1.setActionCommand("Colocar Estampa");
        jButton1.setLabel("Colocar Estampa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 430, 340, 60);

        jButton2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButton2.setText("←");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 90, 70, 270);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("Estampas Obtenidos");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 10, 280, 40);
        jLabel4.getAccessibleContext().setAccessibleName("Estampas Obtenidos");

        jButton3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButton3.setText("→");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(470, 100, 70, 270);

        jButton4.setText("Abrir Más Sobres ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(180, 70, 180, 25);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 360, 290, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("jLabel5");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 390, 290, 19);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static int Pos=0;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Pos++;
        
        if(Pos>8){Pos=0;}
        if(MenuUsuarios.Estampas[Pos][4]==null){Pos=0;}
        
        jLabel2.setIcon(new ImageIcon(MenuUsuarios.Estampas[Pos][4]));
        
        EnlaceJugadores Jugadores = new EnlaceJugadores();
        EnlaceEquipos Equipos = new EnlaceEquipos();
        
        
        if(MenuUsuarios.Estampas[Pos][3].equals("0")){
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        }else{
            
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        }
        
        
        
        
        
        jLabel5.setText(Jugadores.DevolverJugador(Integer.parseInt(MenuUsuarios.Estampas[Pos][1])));
        jLabel6.setText(Equipos.DevolverEquipo(Integer.parseInt(MenuUsuarios.Estampas[Pos][2])));
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pos--;
        
        if(0>Pos){Pos=MenuUsuarios.ult-1;}
        
        jLabel2.setIcon(new ImageIcon(MenuUsuarios.Estampas[Pos][4]));
        
        EnlaceJugadores Jugadores = new EnlaceJugadores();
        EnlaceEquipos Equipos = new EnlaceEquipos();
        
        
        if(MenuUsuarios.Estampas[Pos][3].equals("0")){
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        }else{
            
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));
        }
        
        
        
        
        
        jLabel5.setText(Jugadores.DevolverJugador(Integer.parseInt(MenuUsuarios.Estampas[Pos][1])));
        jLabel6.setText(Equipos.DevolverEquipo(Integer.parseInt(MenuUsuarios.Estampas[Pos][2])));
        
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        MenuUsuarios User = new MenuUsuarios();
        User.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EnlaceRepetidas Repe = new EnlaceRepetidas();

        NodoRepetidas Rep = Repe.Existencia(Integer.parseInt(MenuUsuarios.Estampas[Pos][0]));
        if (Rep.Pegada.equals("1")) {
            JOptionPane.showMessageDialog(null, "Esta Estampa U Otra del mismo tipo Ya Ha Sido Pegada ");
        } else {
            Rep.Pegada = "1";
            Rep.Cantidad = Rep.Cantidad + 1;
            EnlaceEstampasUsuarios Enl = new EnlaceEstampasUsuarios();

            NodoEstampasUsuario EstamU = Enl.Existencia(Integer.parseInt(MenuUsuarios.Estampas[Pos][0]));
            if (EstamU != null) {
                Enl.Limpiar(EstamU);
            } else {
                JOptionPane.showMessageDialog(null, "Nulo");
            }

            JOptionPane.showMessageDialog(null, "Estampa Colocada En El Álbum, abre más estampas para ver tu progreso");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sobres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sobres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sobres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sobres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
